### ISSUE TITLE
Remove temporary files and backup files

### ISSUE THREAD

**Issue by BlueAndi** [NewTec-GmbH/esp32-can-iot#12]
Please remove temporary files and backup files in 
```esp32-can-iot/Hardware/010_Implementation/```

Is the desktop.ini file in the root folder necessary?

**Comment by gabryelreyes** [comment]
Desktop.ini file deleted. 
Files in /Hardware/010_Implementation/ were packed in a ZIP, without the backup files, to reduce size.

**Comment by BlueAndi** [comment]
.zip not necessary. Some files are ASCII files you could diff them for changes. With the .zip you won't have this advantage.
