### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Slenkis** [NewTec-GmbH/esp32-can-iot#17]
### My ```platformio.ini``` file:
```ini
[env:esp32_HW_Ver_1.1]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM20
monitor_port = COM20
monitor_speed = 115200
lib_deps = 
    me-no-dev/AsyncTCP@^1.1.1
    me-no-dev/ESP Async WebServer@^1.2.3
    CAN
    FS
    SPIFFS
    DNSServer
build_flags=
    -std=c++11
    -Wall
    -Wextra
    -O3
    -Wl,-Map,firmware.map
    -Ilib/Lawicel
    -Ilib/WebServer
    -Isrc/Adapters
    -Ilib/IO
    -Ilib/Settings
build_unflags = 
    -Os
    -g3
lib_ignore =
    Test
```
### Build log: https://pastebin.com/huNsGX4y

OS: Win10 PRO x64 21H2
VSCode: v1.74
PlatformIO: 6.1.5
 - framework-arduinoespressif32 @ 3.20005.220925 (2.0.5)
 - tool-esptoolpy @ 1.40201.0 (4.2.1)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3

**Comment by gabryelreyes** [comment]
Hi, this project has not been worked on for some time, and there has been some breaking changes since then. But I may have found a quick fix: Add `#include <Websocket.h>` to main.cpp

If you then get [this](https://github.com/me-no-dev/ESPAsyncWebServer/issues/1147) error: Change your platformio.ini to use older platform version: `platform = espressif32@3.5.0`

**Comment by Slenkis** [comment]
I'm trying to use your project in a bundle of esp32 + vp230... for CAN Hacker v2.00.02 via USB

I downgraded the version, removed the build flags and moved the library dependency to include. now it is assembled without errors.

`platformio.ino`:
```ino
[env:esp32_HW_Ver_1.1]
platform = espressif32 @ ~3.5.0
board = az-delivery-devkit-v4
framework = arduino
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
lib_deps =
    me-no-dev/AsyncTCP@^1.1.1
    me-no-dev/ESP Async WebServer@^1.2.3
    CAN
    FS
    SPIFFS
    DNSServer
lib_ignore = Test
```

![image](https://user-images.githubusercontent.com/30866426/209471423-3a2fbc4e-ec39-413e-89d9-049c87d65f73.png)

**Comment by Slenkis** [comment]
Now there is a problem when reading NVS settings..
In serial port after reset:
```
rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
[E][Preferences.cpp:472] getString(): nvs_get_str len fail: SerialBaud NOT_FOUND
10.1.1.183
WebSocket client #1 connected from 10.1.1.2
[E][Preferences.cpp:472] getString(): nvs_get_str len fail: CanBaud NOT_FOUND
[E][Preferences.cpp:472] getString(): nvs_get_str len fail: CanBaud NOT_FOUND
```
In browser:
![image](https://user-images.githubusercontent.com/30866426/209471607-1f75a564-f675-4c48-914c-5f2b86c51314.png)

# &

CAN Hacker connected to esp, but it cannot receive and send packets

**Comment by gabryelreyes** [comment]
The NVS Errors are not fatal. This just means that there are no parameters stored on the NVS yet.
Regarding Sending and Receiving, are you correctly setting your Baudrate and Opening the CAN Channel using the Lawicel Commands?

Regarding the errors on the Web Interface, you can open the web console to read which errors occur in the Javascript code of the frontend

**Comment by Slenkis** [comment]
When send Lawicel Command ("D[CR]") from browser:
![image](https://user-images.githubusercontent.com/30866426/209473550-9e9fc653-fbdb-48f2-b91c-73b41918cbce.png)

resistance between CAN L and CAN H = 60omh, 
voltage between CAN L (or CAN H) and GND = 1.5v (!!!!)

**Comment by gabryelreyes** [comment]
This should not have anything to do with CAN, as the D command was only implemented to read the current status of the system and send it to the web interface periodically. It has no influence on the Bus itself: [implementation here](https://github.com/NewTec-GmbH/esp32-can-iot/blob/25d864e3779b2deda0d8252bbd4cc9b17b63a298/Coding/fw/lib/Lawicel/Lawicel.cpp#L1470-L1494)

Edit: [Here](https://github.com/NewTec-GmbH/esp32-can-iot/blob/master/Coding/fw/lib/Lawicel/README.md) to the Documentation on the "D" Command

You could try activating the auto-start, in that way the start values will be saved in the NVM.

**Comment by gabryelreyes** [comment]
Have you opened the CAN Channel? Looks like you have not (from the screenshot of the console). That could explain the voltages you are reading.

Please read the Lawicel Documentation on how to open the channel ("S" command to set a Baudrate. "O" command to open the channel)

You could try sending S6 to set it to 500 kbps, and then O to open the channel. And then measure again.

**Comment by Slenkis** [comment]
Channel does not open.. And autostart dont saved

![image](https://user-images.githubusercontent.com/30866426/209476945-c483481c-e10a-4650-9d4d-2cb442b97f72.png)
![image](https://user-images.githubusercontent.com/30866426/209476952-fc3cb25b-8721-4b49-bed4-724afae85637.png)

**Comment by Slenkis** [comment]
Arduino Uno + MCP2515 + TJA1050
ESP32 + VP230 (SN65HVD230D)

<details>
<summary>From Arduino to ESP32</summary>

![image](https://user-images.githubusercontent.com/30866426/209477866-27b00401-0c02-4b4a-a35e-e33b20b8b3fd.png)

</details>
<details>
<summary>From ESP32 to Arduino</summary>

![image](https://user-images.githubusercontent.com/30866426/209477976-afec7684-96f7-4528-985b-ba19f904e011.png)


</details>

**Comment by gabryelreyes** [comment]
Are you receiving any confirmation or message each time you send a command? The console should be answer with OK or Error each time you try to open the channel.

Could you please try it using the Serial Interface?

``` cpp
static Lawicel gProtocolLawicel(gSerialAdapter, gSja1000Adapter, gFlashAdapter);

void setup()
{
    Board::init();
    if (!gProtocolLawicel.begin())
    {
        Board::haltSystem();
    }
}

void loop()
{
    if (!gProtocolLawicel.executeCycle())
    {
        Board::blinkError(250);
    }
}

```

Then you can send S6 and O through the serial monitor, and it should answer with 0x13 (OK) or 0x07 (Error).

If this works and you can send messages, then the problem is in the websocket, but if it does not work and you cannot send messages with it, then the problem is somewhere else.

**Comment by Slenkis** [comment]
I am open Arduino IDE serial monitor, reset ESP32 and send `O[CR]`. I didn't get anything in response...

![image](https://user-images.githubusercontent.com/30866426/209478579-5ff911cd-56af-49ed-8ac8-6e3e0b6d868c.png)

**Comment by gabryelreyes** [comment]
Does the Serial Monitor append the `[CR]` (also seen as `\r`) automatically, or are you writing it yourself? Normally the Serial monitor appends it but it could you could have a different configuration

**Comment by Slenkis** [comment]
Without `[CR]` word after `O` (see photo) the result has not changed.. 

![image](https://user-images.githubusercontent.com/30866426/209478853-3eaf1b0e-625f-4255-b626-6dd858523eaf.png)

**Comment by gabryelreyes** [comment]
Yes, you dont have to write the word `CR` but only `O`. But this is weird, as I just tested it and the ESP32 responds as it should.

Have you tested the ESP32 with the VP230 using only a CAN Bus Example? [Example](https://github.com/sandeepmistry/arduino-CAN/blob/master/examples/CANReceiver/CANReceiver.ino)

I do not have a transceiver with me right now in order to further diagnose your problem, but I will test in a couple of day as soon as I have one.

**Comment by gabryelreyes** [comment]
![image](https://user-images.githubusercontent.com/66941456/209479135-6302e438-1660-42b3-bd7e-72af494e86cf.png)

This is the desired response:
Sent `S6`. Responded `0D`
Sent `O`. Responded `0D`
Sent `C`. Responded `0D`
(... Repeated that a couple of times to check it works...)

Sent `C` after is another `C`. Responded `07` (Error) as the CAN channel was already closed.

**Comment by Slenkis** [comment]
May be my vp230 is died after installing in mcp2515 (5v vin)..

**Comment by Slenkis** [comment]
in arduino this framework: https://github.com/autowp/arduino-canhacker
voltage between canH (or canL) and GND = 2.1v
resistance between canH and canL = 60ohm

![image](https://user-images.githubusercontent.com/30866426/209480200-57bdbe47-ea15-4e3c-8142-0c55c4e702ad.png)

**Comment by gabryelreyes** [comment]
Resistance and Voltage are sadly not a good indicator for CAN Bus given that it is a high speed bus. It would be better to inspect it using an oscilloscope instead.

Were you able to use the example I posted before? With it you can be certain that your hardware/tranceiver/connections work.

**Comment by Slenkis** [comment]
esp32 + vp230 and can example. from elm327 send packet with data=2323 (dec)
serial monitor 115200baud: https://pastebin.com/nBB9AwCp (infinity messages)

**Comment by gabryelreyes** [comment]
Okay so the hardware works :D As I mentioned before, I do not have the means to test this further right now, but I will on the next couple of days. I am sorry you have this problem and I will try to tackle this as soon as I can

**Comment by Slenkis** [comment]
ESP32 send packets to Arduino (script from example folder)

![image](https://user-images.githubusercontent.com/30866426/209481068-a38637fc-4a43-4e5f-b1ed-c37e1474257f.png)

**Comment by gabryelreyes** [comment]
I just wrote a dummy CAN Adapter as I dont have a tranceiver, and it works out-of-the-box with CANHacker v2.00.02. I am able to send and receive data and send it through USB to CANHacker. 

![image](https://user-images.githubusercontent.com/66941456/209482294-7e9fa3e2-1aec-4b66-bf60-5cb7274ceb67.png)


It is weird that the example says that it is sending messages but you dont receive them. Do you have 2 x 120 Ohm resistors in parallel? Do you have another ESP32 and vp230 to test? Or other MCP2515 to check your Arduino setup?

I do not think that your problem has any more to do with this project, but with your setup. If the CAN Examples dont work, the problem is not (completely) here. Make sure the receive and send examples work first :)

**Comment by Slenkis** [comment]
I am waiting for the results of your esp32 + vp230 test with code from master branch.

**Comment by gabryelreyes** [comment]
![image](https://user-images.githubusercontent.com/66941456/209801796-8e3e3db7-2773-4202-ae3f-6a9ad02b24db.png)

Test setup:
ESP32 -> SN65HVD23x Tranceiver (Analog to VP230) -> PCAN USB
You can check the exact connections/schematic in the Hardware Folder.

Here you can see that CANHacker works with the master branch. The code in main.cpp has to be modified a bit in order to use the Serial Interface instead of the websocket (as done before in [here](https://github.com/NewTec-GmbH/esp32-can-iot/issues/17#issuecomment-1364719426))

**Comment by Slenkis** [comment]
can you send a photo of how your vp230 is connected to the esp32?

<details>
  <summary>My setup (pin 4 is CRX, pin 5 is CTX)</summary>

![esp32_vp230_connection](https://user-images.githubusercontent.com/30866426/209943375-3ced63d1-ce5a-41a8-9ff3-8e390fb9748e.jpg)

</details>

**Comment by gabryelreyes** [comment]
I am using the Hardware developed for this project. You can see all the schematics and pictures in the hardware folder, using KiCad. But the connections are the same as in the CAN library and the same that you have: 4 is CRX and 5 is CTX. Do you have any other pins available in the transceiver? Maybe you are in loopback mode or sleep mode. Check the datasheet please. And as I mentioned, try to get the examples of the CAN library to work and then come back to this project

**Comment by gabryelreyes** [comment]
Please check [this](https://github.com/sandeepmistry/arduino-CAN/issues/75) is not your case.

**Comment by gabryelreyes** [comment]
Documentation on the connection to CANHacker can be now found [here](https://github.com/NewTec-GmbH/esp32-can-iot/blob/master/Coding/fw/doc/CANHacker.md)

**Comment by Slenkis** [comment]
> Documentation on the connection to CANHacker can be now found [here](https://github.com/NewTec-GmbH/esp32-can-iot/blob/master/Coding/fw/doc/CANHacker.md)

### Code from the [documentation](../blob/master/Coding/fw/doc/CANHacker.md) doesn`t build because there are no necessary libraries

#### BUILD is OK, imports from master branch:

```cpp
#include <Arduino.h>
#include "Lawicel.h"
#include "SerialAdapter.h"
#include "CANAdapter.h"
#include "NVMAdapter.h"
// #include "WebSocketAdapter.h" // not used
#include "Board.h"
#include "WLAN.h"
```

#### BUILD is FAILED, imports from [md](../blob/master/Coding/fw/doc/CANHacker.md):

```cpp
#include <Arduino.h>
#include "Lawicel.h"
#include "Board.h"
#include "SerialAdapter.h"
#include "CANAdapter.h"
#include "NVMAdapter.h"
```

**Comment by Slenkis** [comment]
and my Aduino uno + MCP2515 (with tja1050) + [this scetch](https://github.com/autowp/arduino-canhacker/blob/master/examples/softwareserial_debug/softwareserial_debug/softwareserial_debug.ino) => now is working... im mix up CAN H and L wires.. sorry

my esp32 + vp230 + [your code after fix](https://github.com/NewTec-GmbH/esp32-can-iot/blob/master/Coding/fw/doc/CANHacker.md) => now he listens to packets, but he can't send anything... CTX pin has 3.3v, CRX has 1.8v; can H & L pins has 1.5v if transiver not connected to can bus

**Comment by gabryelreyes** [comment]
The fix not building is a sad inconvinience, but it should not have an effect on the functionality of the library. In the upcoming weeks I will fix all those build and configuration issues. Thanks for bringing this to my attention 👍 

Regarding your vp230 problem, make sure you check the following:

- [These](https://github.com/NewTec-GmbH/esp32-can-iot/tree/master/Coding/fw/lib/CAN/examples) examples work. Sender and receiver. That way you can be sure your controller and tranceiver work properly
- Do you have you two 120 Ohm terminating resistors?
- Are CTX and CRX correctly and securely connected to the ESP32?
- Do you have more than one CAN Node on your Bus? If the ESP32 is alone, then it will fail on transmit
- Check your controller is not on listen-only mode
- Erase the Flash memory of the ESP32 and upload the firmware again

If after all of these, it still does not work, then we can continue looking for problems in this project.

**Comment by Slenkis** [comment]
WARNING: my vp230 transiver may be damaged and packets listening only...

I have two 120 Ohm terminating resistors. Controllers in normal mode. I erased the memory on the esp32.
[This sketch](https://github.com/Seeed-Studio/Seeed_Arduino_CAN/tree/master/examples/canbus-monitor) is uploaded to arduino uno. Works fine! Tested with car bus.

### From [arduino uno + mcp2515] to [esp32 + vp230]: 
![image](https://user-images.githubusercontent.com/30866426/215293543-cd654859-a06a-40bf-98ae-bd99727938f4.png)

### From [esp32 + vp230] to [arduino uno + mcp2515]: 
![image](https://user-images.githubusercontent.com/30866426/215293932-e12d0972-32ca-4f16-a2fa-7d929e1ff79b.png)

### From [ELM327] to [arduino uno + mcp2515] & [esp32 + vp230]: 
![image](https://user-images.githubusercontent.com/30866426/215294372-ee623269-ead2-4030-ad40-b40d274bb252.png)

**Comment by gabryelreyes** [comment]
Please check the Sender and receiver examples mentioned above. that way you can know if the tranceiver is damaged. 
Also Check [this](https://github.com/sandeepmistry/arduino-CAN/issues/75) is not your case.

**Comment by Slenkis** [comment]
## Please, add fix from this [PR](https://github.com/sandeepmistry/arduino-CAN/pull/97/) to your library. 
### I patched ESP32SJA1000.cpp manually from [PR97](https://github.com/sandeepmistry/arduino-CAN/pull/97) and [PR71](https://github.com/sandeepmistry/arduino-CAN/pull/71). Works fine, but esp32 + vp230 not sent packets (see next screenshots)!
### ESP32 + vp230 with this fix stable listens to packets from can bus devices.
![image](https://user-images.githubusercontent.com/30866426/215611964-08df94cd-49f4-4c76-8b06-d5daccc43e96.png)



### ESP32 + vp230 does not send packets to bus. Also I tried to use this [PR](https://github.com/sandeepmistry/arduino-CAN/pull/97/), but but the packets were not sent to the bus.
![image](https://user-images.githubusercontent.com/30866426/215603104-bc307eb4-aff5-4b3b-aefe-207e02ebc54a.png)

**Comment by gabryelreyes** [comment]
The library is done in such a way, that you can implement your own CANAdapter according to your needs/controller/tranceiver. You can delete the CAN library provided and write your own CANAdapter using the library that works for you at best. You only have to implement the functions declared in CANInterface.h
